# Generated by Django 2.0.5 on 2018-05-23 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 8, 53, 48, 636763, tzinfo=utc)),
        ),
    ]
