# Generated by Django 2.0.5 on 2018-05-23 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_shift_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
