# Generated by Django 2.0.5 on 2018-05-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0006_auto_20180523_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
