# Generated by Django 2.0.1 on 2018-02-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_length', models.IntegerField(default=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
